export const timeSlots = [
  "7:40-8:30",
  "8:30-9:20",
  "9:20-10:10",
  "10:10-11:00",
  "11:00-11:50",
  "11:50-12:40",
  "12:40-13:30",
  "13:30-14:20",
  "14:20-15:10",
  "15:10-16:00",
  "16:00-16:50",
  "16:50-17:40",
  "17:40-18:30",
  "18:30-19:20",
  "19:20-20:10",
  "20:10-21:00",
];

export const GAConfig: ISetting = {
  id: 1,
  maximum_generations: 70,
  minimum_population: 61,
  elite_percent: 0.05,
  ending_time: 15,
  generation_tolerance: 1526,
  deviation_tolerance: 57,
  lunchbreak: false,
  starting_time: 0,
  idle_time: 0,
  subject_placement: 93,
  mutation_rate_adjustment_trigger: 3.26,
  mutation_rate_base: 4.5,
  mutation_rate_step: 5.2,
  maximum_population: 112,
  maximum_fitness: 97,
  timeslots: timeSlots,
};

export const daysOfWeek = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
export const defaultSchedule = [
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
  [
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
    "Available",
  ],
];
